[project]
name = "llm-twin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromedriver-autoinstaller>=0.6.4",
    "loguru>=0.7.3",
    "pytest>=8.4.0",
    "selenium>=4.33.0",
    "webdriver-manager>=4.0.2",
]

