use="chrome"

[chrome.options]
args = [
	"no-sandbox"
	, "disable-dev-shm-usage"
	, "disable-popup-blocking"
	, "disable-background-networking"
	, "ignore-certificate-errors"
]

[chrome.options.kwargs]
headless = "new"
log-level = 3
user-data-dir = ""
data-path = ""
disk-cache-dir = ""
remote-debugging-port = 9226

