use="chrome"

[chrome.options]
args = [
	"no-sandbox"
	, "disable-dev-shm-usage"
	, "disable-popup-blocking"
	, "disable-background-networking"
	, "ignore-certificate-errors"
]

[chrome.options.kwargs]
headless                = "new"
log-level               = 3
user-data-dir           = "" # Leave empty to use a temp dir
data-path               = "" # Leave empty to use a temp dir
disk-cache-dir          = "" # Leave empty to use a temp dir
remote-debugging-port 	= 9226

[edge.options]
args = [
	"no-sandbox"
	, "disable-dev-shm-usage"
	, "disable-popup-blocking"
	, "disable-background-networking"
	, "ignore-certificate-errors"
]

[edge.options.kwargs]
headless                = "new"
log-level               = 3
user-data-dir           = "" # Leave empty to use a temp dir
data-path               = "" # Leave empty to use a temp dir
disk-cache-dir          = "" # Leave empty to use a temp dir
remote-debugging-port 	= 9226

