supported_drivers:
  - name: chrome
    arguments:
      - no-sandbox
      - headless:
          - value: new
      - disable-dev-shm-usage
      - log-level:
          - value: 3
      - disable-popup-blocking
      - disable-notifications
      - disable-extensions
      - disable-background-networking
      - ignore-certificate-errors
      - user-data-dir:
          - path: null
      - data-path:
          - path: null
      - disk-cache-dir:
          - path: null
      - remote-debugging-port:
          - value: 9226
