[name]
path=""
tag="h1"
[name.kwargs]
class_="inline t-24 v-align-middle break-words"


[about]
path=""
tag="h1"
[about.kwargs]
class_="display-flex ph5 pv3"

[main-page]
path=""
tag="main"
[main-page.kwargs]
class_="display-flex ph5 pv3"

[experience]
path="/details/experience/"
tag="div"
[experience.kwargs]
class_="pvs-list__container"

[education]
path="/details/education/"
tag="div"
[education.kwargs]
class_="pvs-list__container"

[posts]
path="/recent-activity/all/"
tag="div"
[posts.kwarsg]
class_="pv-recent-activity-detail__core-rail"

[licenses-and-certifications]
path="/details/certifications/"
tag="div"
[licenses-and-certifications.kwargs]
class_="pvs-list__container"
